# -*- coding: utf-8 -*-
"""iot_data_pipeline .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WWMQzxI2MhWetU9DlEXi_BcM48fRuGLh
"""

import pandas as pd
import numpy as np

print("INITIATING FLEET-WIDE IIoT DATA AGGREGATION PIPELINE...")

# 1. DATA INGESTION
try:
    df = pd.read_csv('iot_telemetry.csv')
except FileNotFoundError:
    print("CRITICAL ERROR: 'iot_telemetry.csv' not found.")
    exit()

df.columns = df.columns.str.strip().str.lower()
df['timestamp'] = pd.to_datetime(df['timestamp'])
df = df.sort_values(by=['machine_id', 'timestamp'])

# Create a proxy column to count total minutes (1 row = 1 minute)
df['row_count'] = 1

# 2. FLEET AGGREGATION (Hourly blocks using actual numeric schema)
aggregation_rules = {
    'temperature': 'mean',
    'vibration_level': 'max',
    'power_consumption': 'sum',
    'downtime': 'mean',          
    'error_rate': 'mean',       
    'efficiency_score': 'mean', 
    'row_count': 'sum'          
}

fleet_hourly = df.groupby(['machine_id', pd.Grouper(key='timestamp', freq='h')]).agg(aggregation_rules).reset_index()
fleet_hourly.rename(columns={'row_count': 'total_minutes'}, inplace=True)

# 3. ALIGN WITH FRONTEND SCHEMA REQUIREMENTS
fleet_hourly['FAILURE'] = fleet_hourly['downtime'].clip(upper=fleet_hourly['total_minutes'])
fleet_hourly['RUNNING'] = fleet_hourly['total_minutes'] - fleet_hourly['FAILURE']
fleet_hourly['RUNNING'] = fleet_hourly['RUNNING'].clip(lower=0)
fleet_hourly['IDLE'] = 0

# 4. OEE MATHEMATICAL TRANSLATION
fleet_hourly['Availability'] = np.where(
    fleet_hourly['total_minutes'] > 0, 
    fleet_hourly['RUNNING'] / fleet_hourly['total_minutes'], 
    0
)

# Scale native efficiency score to standard 0.0-1.0 percentage
fleet_hourly['Performance'] = (fleet_hourly['efficiency_score'] / 100).clip(upper=1.0)

# Quality is the inverse of the error rate
fleet_hourly['Quality'] = (1.0 - fleet_hourly['error_rate']).clip(lower=0.0)

# Final OEE
fleet_hourly['OEE_Score'] = fleet_hourly['Availability'] * fleet_hourly['Performance'] * fleet_hourly['Quality']

# Proxy physical part counts for the UI charts
IDEAL_HOURLY_PRODUCTION = 300
fleet_hourly['produced_parts'] = fleet_hourly['Performance'] * IDEAL_HOURLY_PRODUCTION
fleet_hourly['defective_parts'] = fleet_hourly['produced_parts'] * fleet_hourly['error_rate']

# Ensure exact column match for Streamlit rendering
final_columns = ['machine_id', 'timestamp', 'temperature', 'vibration_level', 'power_consumption', 
                 'RUNNING', 'IDLE', 'FAILURE', 'produced_parts', 'defective_parts', 
                 'Availability', 'Performance', 'Quality', 'OEE_Score']
fleet_hourly = fleet_hourly[final_columns]

# 5. PARQUET EXPORT
output_file = 'fleet_iiot_metrics.parquet'
fleet_hourly.to_parquet(output_file, index=False)
print(f"PIPELINE COMPLETE. Data exported to: {output_file}")
